mcc('-m', '-R', '-nodisplay', ...
    '-R', '-singleCompThread', ...
    '-d', fileparts(which('run_mreg_recon_tool_recon.sh')), ...
    'mreg_recon_tool_recon.m', ...
    'identityOperator.m', ...
    'finiteDifferenceOperator.m', ...
    'waveletDecompositionOperator.m', ...
    'L1Norm.m', ... 
    'dbwavfX.m');